{{- range $name, $config := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-svc
spec:
  replicas: {{ $config.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $.Values.global.ecrRegistry }}/{{ $config.image }}:{{ $config.tag }}"
          ports:
            - containerPort: {{ $config.port }}
          envFrom:
            - configMapRef:
                name: streamingapp-config
            - secretRef:
                name: streamingapp-secret
          livenessProbe:
            httpGet:
              path: /
              port: {{ $config.port }}
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: {{ $config.port }}
            initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-svc
spec:
  type: ClusterIP
  ports:
    - port: {{ $config.port }}
      targetPort: {{ $config.port }}
  selector:
    app: {{ $name }}
---
{{- end }}
