apiVersion: v1
kind: ConfigMap
metadata:
  name: streamingapp-config
data:
  MONGO_URI: "mongodb://mongo:27017/streamingdb"
  AWS_REGION: {{ .Values.global.awsRegion | quote }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: streamingapp-config
data:
  MONGO_URI: "mongodb://mongo:27017/streamingdb"
  AWS_REGION: {{ .Values.global.awsRegion | quote }}
  PORT: "3000"
  PORT_AUTH: "3001"
  PORT_STREAM: "3002"
  PORT_ADMIN: "3003"
  PORT_CHAT: "3004"
