apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: {{ .Values.mongo.port }}
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.mongo.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: {{ .Values.mongo.port }}
  selector:
    app: mongo
