apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: auth-service
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-service
spec:
  ports:
  - port: 3002
    targetPort: 3002
  selector:
    app: streaming-service
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  ports:
  - port: 3003
    targetPort: 3003
  selector:
    app: admin-service
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  ports:
  - port: 3004
    targetPort: 3004
  selector:
    app: chat-service
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend
