global:
  awsRegion: "us-east-1"
  ecrRegistry: "985368780045.dkr.ecr.us-east-1.amazonaws.com"

mongo:
  storageSize: 5Gi
  port: 27017

services:
  auth:
    image: "streaming-auth"
    tag: "1.0.0"
    replicas: 2
    port: 3001
  streaming:
    image: "streaming-service"
    tag: "1.0.0"
    replicas: 2
    port: 3002
  admin:
    image: "admin-service"
    tag: "1.0.0"
    replicas: 2
    port: 3003
  chat:
    image: "chat-service"
    tag: "1.0.0"
    replicas: 2
    port: 3004
  frontend:
    image: "frontend-service"
    tag: "1.0.0"
    replicas: 2
    port: 80

ingress:
  host: "streamingapp.local"
