apiVersion: v1
kind: Secret
metadata:
  name: streamingapp-secret
type: Opaque
stringData:
  JWT_SECRET: "AcademicSecretKey123!"
  AWS_ACCESS_KEY_ID: "AKIA6K3EOLUGWPQSL2I6example"
  AWS_SECRET_ACCESS_KEY: "nQKiQ5a5rkQt7TPd2fIHZl7F6zrCK0aECrCLJiS6"
